Fix exception wrong place and entity schematics serialization
BuildCraft/BuildCraftAPI pull request #20
Opened 2017-05-24 13:11 UTC by afdw

2017-05-24 22:55 UTC, AlexIIL requested changes
Looks good! Minor issue though: all readFromNbt methods should throw ````InvalidDataInputException```` rather than just ````Exception````

2017-05-24 22:56 UTC, AlexIIL requested changes
Throw InvalidDataInputException rather than any Exception

2017-05-24 22:56 UTC, AlexIIL commented on api/buildcraft/api/schematics/ISchematicEntity.java
> +    void deserializeNBT(NBTTagCompound nbt) throws Exception;
Specifically here

2017-05-24 22:56 UTC, AlexIIL commented on api/buildcraft/api/schematics/ISchematicBlock.java
>      int FLUID_LEVEL = 1;
Specifically below this point (````deserialiseNBT````)

2017-05-25 04:31 UTC, afdw commented
@AlexIIL done

2017-05-25 09:35 UTC, AlexIIL approved these changes

2017-05-25 09:35 UTC, AlexIIL commented
Thanks

2017-05-25 09:36 UTC, merged